<?php

declare(strict_types=1);

/*
 * Generates src/Types.php: PHPStan/Psalm array-shape types for every object of the
 * GaiaDesk API contract, from its bundled OpenAPI document (api/openapi.json in the
 * GaiaDesk source, whose schemas include the CLI's own from client/schema.json).
 *
 *   php tools/gen-types.php path/to/openapi.json > src/Types.php
 */

if ($argc < 2) {
    fwrite(\STDERR, "usage: php tools/gen-types.php <openapi.json>\n");
    exit(2);
}
$doc = json_decode((string) file_get_contents($argv[1]), true, 512, \JSON_THROW_ON_ERROR);
$schemas = $doc['components']['schemas'];

/** @param array<string, mixed> $s */
function resolve(array $s, array $schemas): array
{
    while (isset($s['$ref'])) {
        $s = $schemas[basename($s['$ref'])];
    }

    return $s;
}

function literal(mixed $v): string
{
    return is_string($v) ? "'".str_replace("'", "\\'", $v)."'" : json_encode($v);
}

/** @param array<string, mixed> $s */
function phpType(array $s, array $schemas, int $depth = 0): string
{
    if (isset($s['$ref'])) {
        return basename($s['$ref']);
    }
    if (array_key_exists('const', $s)) {
        return literal($s['const']);
    }
    if (isset($s['enum'])) {
        return implode('|', array_map('literal', $s['enum']));
    }
    if (isset($s['allOf'])) {
        $props = [];
        $required = [];
        foreach ($s['allOf'] as $part) {
            $p = resolve($part, $schemas);
            if (isset($p['allOf'])) {
                $p = flatten($p, $schemas);
            }
            foreach ($p['properties'] ?? [] as $k => $v) {
                $props[$k] = isset($props[$k]) && !isset($v['$ref']) && !isset($v['type']) && !isset($v['oneOf']) ? $props[$k] : $v;
            }
            $required = array_merge($required, $p['required'] ?? []);
        }

        return shape($props, $required, $schemas, $depth);
    }
    foreach (['oneOf', 'anyOf'] as $k) {
        if (isset($s[$k])) {
            $types = array_unique(array_map(static fn (array $x): string => phpType($x, $schemas, $depth), $s[$k]));

            return implode('|', $types);
        }
    }
    $type = $s['type'] ?? null;
    if (is_array($type)) {
        $parts = [];
        foreach ($type as $t) {
            $parts[] = phpType(['type' => $t] + array_diff_key($s, ['type' => 1]), $schemas, $depth);
        }

        return implode('|', array_unique($parts));
    }

    return match ($type) {
        'string' => 'string',
        'integer' => 'int',
        'number' => 'int|float',
        'boolean' => 'bool',
        'null' => 'null',
        'array' => 'list<'.(isset($s['items']) ? phpType($s['items'], $schemas, $depth) : 'mixed').'>',
        'object' => isset($s['properties']) ? shape($s['properties'], $s['required'] ?? [], $schemas, $depth) : 'array<string, '.(is_array($s['additionalProperties'] ?? null) ? phpType($s['additionalProperties'], $schemas, $depth) : 'mixed').'>',
        default => isset($s['properties']) ? shape($s['properties'], $s['required'] ?? [], $schemas, $depth) : 'mixed',
    };
}

/** @param array<string, mixed> $s */
function flatten(array $s, array $schemas): array
{
    $props = [];
    $required = [];
    foreach ($s['allOf'] as $part) {
        $p = resolve($part, $schemas);
        if (isset($p['allOf'])) {
            $p = flatten($p, $schemas);
        }
        $props = array_merge($props, $p['properties'] ?? []);
        $required = array_merge($required, $p['required'] ?? []);
    }

    return ['type' => 'object', 'properties' => $props, 'required' => $required];
}

/**
 * @param array<string, array<string, mixed>> $props
 * @param list<string>                        $required
 */
function shape(array $props, array $required, array $schemas, int $depth): string
{
    ksort($props);
    $fields = [];
    foreach ($props as $k => $v) {
        $fields[] = $k.(in_array($k, $required, true) ? '' : '?').': '.phpType($v, $schemas, $depth + 1);
    }

    return 'array{'.implode(', ', $fields).'}';
}

$names = array_keys($schemas);
sort($names);
$lines = [];
foreach ($names as $name) {
    $lines[] = ' * @phpstan-type '.$name.' '.phpType($schemas[$name], $schemas);
}
$version = $doc['info']['version'] ?? '?';
$out = <<<PHP
<?php

declare(strict_types=1);

namespace GaiaDesk;

/**
 * The JSON shapes of the GaiaDesk API (v{$version}), field for field: what every method
 * returns, as PHPStan/Psalm array shapes. GENERATED by tools/gen-types.php from the API's
 * OpenAPI contract (which references the CLI's own result types); do not edit by hand.
 *
 * Results are plain PHP arrays (JSON objects decoded with `json_decode(…, true)`); these
 * types are for editors and static analysers. Import one with
 * `@phpstan-import-type ExecResult from \GaiaDesk\Types`. The API may add fields.
 *

PHP;
$out .= implode("\n", $lines)."\n */\nfinal class Types\n{\n    private function __construct()\n    {\n    }\n}\n";
echo $out;
