<?php

declare(strict_types=1);

namespace GaiaDesk;

/**
 * The JSON shapes of the GaiaDesk API (v1.0.0), field for field: what every method
 * returns, as PHPStan/Psalm array shapes. GENERATED by tools/gen-types.php from the API's
 * OpenAPI contract (which references the CLI's own result types); do not edit by hand.
 *
 * Results are plain PHP arrays (JSON objects decoded with `json_decode(…, true)`); these
 * types are for editors and static analysers. Import one with
 * `@phpstan-import-type ExecResult from \GaiaDesk\Types`. The API may add fields.
 *
 * @phpstan-type ApiAuditEvent array{action: string, actor: array{id?: string|null, type?: string}, id: string, metadata: array<string, mixed>, occurred_at_ms: int, stream: string, target?: array{id?: string|null, name?: string|null, type?: string|null}|null}
 * @phpstan-type ApiAuditList array{events: list<ApiAuditEvent>}
 * @phpstan-type ApiDesk array{anytime?: bool|null, app_version?: string|null, desk_id: string, e2e_pub?: string|null, e2e_required?: bool, features?: list<string>, last_failure?: ReachFailure|null, last_ok?: ReachSuccess|null, last_seen?: int|null, name?: string|null, offline_detail?: string, offline_reason?: string, offline_reason_text?: string, offline_since?: int, online: bool, os?: string|null, owner: string|null, probe?: ProbeResult|null, reachable?: bool|null, signal_idle_secs?: int|null, sources: list<string>}
 * @phpstan-type ApiDeskDetail array{anytime?: bool|null, app_version?: string|null, desk_id: string, e2e_pub?: string|null, e2e_required?: bool, features?: list<string>, last_failure?: ReachFailure|null, last_ok?: ReachSuccess|null, last_seen?: int|null, name?: string|null, offline_detail?: string, offline_reason?: string, offline_reason_text?: string, offline_since?: int, online: bool, os?: string|null, owner: string|null, probe?: ProbeResult|null, reachable?: bool|null, signal_idle_secs?: int|null, sources: list<string>, wake: ApiWakeHints}
 * @phpstan-type ApiDeskList array{devices: list<ApiDesk>, identity: Identity, notes: list<string>, sources: list<string>}
 * @phpstan-type ApiE2eAnswer array{e2e: ApiE2eEvents}
 * @phpstan-type ApiE2eBody array{e2e: ApiE2eRequest}
 * @phpstan-type ApiE2eEvents array{events: list<ApiE2eFrame>, v: 1}
 * @phpstan-type ApiE2eFrame array{ciphertext: string, nonce: string, seq: int}
 * @phpstan-type ApiE2eRequest array{ciphertext: string, nonce: string, pub: string, v?: 1}
 * @phpstan-type ApiE2eStreamEvent array{ciphertext: string, event: 'sealed', nonce: string, seq: int}
 * @phpstan-type ApiError array{desk?: string|null, kind: ErrorKind, message: string, reason?: string|null, request_id: string, status?: int}
 * @phpstan-type ApiErrorEnvelope array{e2e?: ApiE2eEvents, error: ApiError}
 * @phpstan-type ApiExecSpec array{admin?: false, argv?: list<string>, command?: string|null, cwd?: string|null, env?: array<string, string>, shell?: Shell, stdin?: string|null, timeout_secs?: int|float|null}
 * @phpstan-type ApiJobFinishedEvent array{created: int, data: array{desk: array{desk_id: string, owner: string}, job: Job}, id: string, type: 'job.finished'}
 * @phpstan-type ApiMintSpec array{cwd?: string|null, expires_secs: int, low_priv?: bool, name: string, scopes: list<'exec'|'shell'|'cp'|'forward'|'jobs'|'screen'>}
 * @phpstan-type ApiReachEvent array{at: int, detail?: string|null, online: bool, reason: string, reason_text: string, version?: string|null}
 * @phpstan-type ApiReachLog array{desk_id: string, events: list<ApiReachEvent>, since: int}
 * @phpstan-type ApiSupportCustomer array<string, string|int|float|bool|null>
 * @phpstan-type ApiSupportMode 'view'|'cobrowse'
 * @phpstan-type ApiSupportSession array{created_at: int, customer: ApiSupportCustomer, customer_present: bool, customer_verified: bool, desk_id?: string|null, end_reason?: string|null, ended_at?: int|null, expires_at: int, id: string, join_code: string, join_url: string, joined_at?: int|null, joined_by?: string|null, mode: ApiSupportMode, origin?: string|null, owner: string, state: 'waiting'|'joined'|'ended'|'expired'}
 * @phpstan-type ApiSupportSessionCreate array{customer?: ApiSupportCustomer, expires_in?: int, mode?: ApiSupportMode, origin?: string}
 * @phpstan-type ApiSupportSessionCreated array{created_at: int, customer: ApiSupportCustomer, customer_present: bool, customer_verified: bool, desk_id?: string|null, embed_token: string, end_reason?: string|null, ended_at?: int|null, expires_at: int, id: string, join_code: string, join_url: string, joined_at?: int|null, joined_by?: string|null, mode: ApiSupportMode, origin?: string|null, owner: string, state: 'waiting'|'joined'|'ended'|'expired'}
 * @phpstan-type ApiSupportSessionEvent array{created: int, data: array{support_session: array{created_at: int, customer: ApiSupportCustomer, customer_verified: bool, end_reason?: string|null, ended_at?: int|null, expires_at: int, id: string, joined_at?: int|null, joined_by?: string|null, mode: ApiSupportMode, origin?: string|null, owner: string, state: 'waiting'|'joined'|'ended'|'expired'}}, id: string, type: 'support.session.joined'|'support.session.ended'}
 * @phpstan-type ApiSupportSessionList array{sessions: list<ApiSupportSession>}
 * @phpstan-type ApiWakeHints array{doorbell_sockets: int, lan_wake: bool}
 * @phpstan-type ApiWakeRequest array{wait_s?: int}
 * @phpstan-type ApiWakeResult array{already_online: bool, desk_id: string, online: bool, rang: array{doorbell: int, lan_helpers: int}, waited_ms: int, woke: bool}
 * @phpstan-type ApiWebhook array{created_at: int, description: string, events: list<ApiWebhookEventType>, id: string, url: string}
 * @phpstan-type ApiWebhookCreate array{description?: string, events: list<ApiWebhookEventType>, url: string}
 * @phpstan-type ApiWebhookCreated array{created_at: int, description: string, events: list<ApiWebhookEventType>, id: string, secret: string, url: string}
 * @phpstan-type ApiWebhookDeleted array{deleted: string}
 * @phpstan-type ApiWebhookEvent array{created: int, data: array{desk: array{desk_id: string, owner: string, reason: string, reason_text: string, version?: string|null, woke_after_ms?: int}}, id: string, type: ApiWebhookEventType}
 * @phpstan-type ApiWebhookEventType 'desk.online'|'desk.offline'|'desk.woke'|'job.finished'|'support.session.joined'|'support.session.ended'
 * @phpstan-type ApiWebhookList array{webhooks: list<ApiWebhook>}
 * @phpstan-type CopyFailure array{message: string, path: string}
 * @phpstan-type CopyResult array{bytes: int, desk: string, destination: string, direction: string, dirs: int, failed: list<CopyFailure>, files: int, resumed_bytes: int, seconds: int|float}
 * @phpstan-type Device array{anytime?: bool|null, app_version?: string|null, desk_id: string, last_failure?: ReachFailure|null, last_ok?: ReachSuccess|null, last_seen?: int|null, name?: string|null, online?: bool|null, os?: string|null, owner?: string|null, probe?: ProbeResult|null, reachable?: bool|null, signal_idle_secs?: int|null, sources: list<string>}
 * @phpstan-type DeviceList array{devices: list<Device>, identity: Identity, notes: list<string>, sources: list<string>}
 * @phpstan-type DiskStat array{free_mb: int, mount: string, total_mb: int}
 * @phpstan-type Error array{desk?: string|null, kind: ErrorKind, message: string, reason?: string|null}
 * @phpstan-type ErrorKind 'usage'|'refused'|'unreachable'|'connection_lost'|'failed'|'protocol'
 * @phpstan-type ExecEvent array{data: string, event: 'stdout'}|array{data: string, event: 'stderr'}|array{event: 'note', message: string}|ExecExit|array{error: Error, event: 'error', exit: int}
 * @phpstan-type ExecExit array{desk: string, duration_ms: int, error?: Error|null, exit: int, mode?: string|null, notes: list<string>, remote_code?: int|null, route?: string|null, shell?: string|null, timed_out: bool}
 * @phpstan-type ExecResult array{desk: string, duration_ms: int, error?: Error|null, exit: int, mode?: string|null, notes: list<string>, remote_code?: int|null, route?: string|null, shell?: string|null, stderr: string, stdout: string, timed_out: bool, truncated: bool}
 * @phpstan-type ExecSpec array{admin?: bool, argv?: list<string>, command?: string|null, cwd?: string|null, env?: array<string, string>, shell?: Shell, stdin?: string|null, timeout_secs?: int|float|null}
 * @phpstan-type Identity array{account?: string|null, source: string}
 * @phpstan-type Job array{by?: string, command: string, ended_at_ms?: int|null, enforcement?: list<string>, exit_code?: int|null, limits?: JobLimits|null, log_bytes?: int, name: string, pid?: int|null, reason?: string|null, started_at_ms: int, state: string}
 * @phpstan-type JobLimits array{cpu_percent?: int|null, keep_awake?: bool|null, mem_mb?: int|null, priority?: string|null}
 * @phpstan-type JobList array{jobs: list<Job>}
 * @phpstan-type JobLogEvent array{data: string, event: 'output'}|array{event: 'end', job: Job}|array{event: 'interrupted'}|array{error: Error, event: 'error'}
 * @phpstan-type JobLogs array{job: Job, output: string}
 * @phpstan-type JobSpec array{command: list<string>, cwd?: string|null, env?: array<string, string>, limits?: JobLimits, name: string, shell?: Shell|null}
 * @phpstan-type JobWaitResult array{job: Job, timed_out: bool}
 * @phpstan-type MintResult array{tokens: list<MintedToken>}
 * @phpstan-type MintSpec array{cwd?: string|null, expires_secs: int, low_priv?: bool, name: string, scopes: list<string>}
 * @phpstan-type MintedToken array{desk: string, secret: string, token: TokenInfo}
 * @phpstan-type ProbeResult array{connect_ms?: int|null, dialled: bool, error?: string|null, hostname?: string|null, kind?: string|null, ok: bool, os?: string|null, route?: string|null, rtt_ms?: int|null}
 * @phpstan-type ReachFailure array{at: int, kind: string, message: string}
 * @phpstan-type ReachSuccess array{at: int, connect_ms?: int|null, route: string, rtt_ms?: int|null}
 * @phpstan-type Revoked array{revoked: string, stopped_sessions: int}
 * @phpstan-type Shell 'default'|'none'|'sh'|'bash'|'zsh'|'cmd'|'pwsh'|'powershell'
 * @phpstan-type StatsReport array{cpu_percent: int|float, cpus: int, desk: string, disks?: list<DiskStat>, hostname: string, jobs_running: int, load?: list<int|float>|null, mem_free_mb: int, mem_total_mb: int, os: string, os_version?: string, uptime_secs: int}
 * @phpstan-type TokenInfo array{cwd?: string|null, expires_at_ms: int, id: string, issued_at_ms: int, label: string, last_used_ms?: int|null, low_priv?: bool, revoked?: bool, scopes?: list<string>}
 * @phpstan-type TokenList array{tokens: list<TokenInfo>}
 */
final class Types
{
    private function __construct()
    {
    }
}
